name: Shell Commands

on: [push]

jobs:
  run-shell-commmand:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello, world!"
      - name: multiline script
        run: |
          node -v
          npm -v
          